name: Pipeline Test Web

on: push 

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
          contents: read
          pages: write
          id-token: write
    environment:
     name: github-pages
     url: https://noeleguimaraes.github.io/automacao-web-robot-serverest/report.html

    steps:
      - name: Clonagem Projeto
        # run: echo Fazendo clone do repositorio na maquina virtual
        uses: actions/checkout@v3

      - name: Configuração do Python
        # run: echo Instalação da versão 3.12 do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalar Dependências do Projeto
        # run: echo Instalação das depedências do Projeto
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Execução dos Testes Web
        # run: echo Executando os testes de API do Robot
        run: |
          robot --outputdir  tests/

      - name: Salvando resultado dos testes
          # run: echo Salvando o Report dos Testes
        uses: actions/upload-artifact@v4 
        if: always()
        with:
            name: resultado-testes
            path: ./reports

      - name: Configurar site de Relatórios dos testes
        uses: actions/configure-pages@v5
        if: always()

      - name: Carregar os resultados
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
           path: reports/

      - name: Subir Site de Relatório dos testes
        id: deployment
        uses: actions/deploy-pages@v4
        if: always()
